# Generated by Django 2.2.10 on 2020-02-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsCategory',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('num_rooms', models.IntegerField()),
                ('descr', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms_category',
            },
        ),
        migrations.CreateModel(
            name='RoomsName',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'rooms_name',
            },
        ),
        migrations.CreateModel(
            name='RoomsBookedStatus',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('booked_status', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomscategory.RoomsName')),
            ],
            options={
                'db_table': 'rooms_booked_status',
            },
        ),
    ]
