# Generated by Django 2.2.10 on 2020-02-26 06:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('id_proof', models.FileField(null=True, upload_to='media/')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
            },
        ),
    ]
