# Generated by Django 2.2.10 on 2020-02-26 06:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDraft',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_bill', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_draft',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('num_people', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('check_indate', models.DateField()),
                ('check_outdate', models.DateField()),
                ('duration', models.IntegerField()),
                ('details', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('guests_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationLogs',
            fields=[
                ('s_no', models.AutoField(primary_key = True)),
                ('log_mode', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('positive', models.BooleanField(default=False)),
                ('log_details', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('room_alotted', django.contrib.postgres.fields.jsonb.JSONField()),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_reservations.Reservation')),
            ],
            options={
                'db_table': 'confirmation_logs',
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('billing_draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_reservations.BillingDraft')),
            ],
            options={
                'db_table': 'billing_payment',
            },
        ),
        migrations.AddField(
            model_name='billingdraft',
            name='confirmation_log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_reservations.ConfirmationLogs'),
        ),
    ]
