# Generated by Django 2.2.10 on 2020-02-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomscategory', '0001_initial'),
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMealCategoryPlan',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('cost_in_rs', models.IntegerField()),
                ('descr', models.TextField()),
                ('mealplans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.MealPlans')),
                ('roomscategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomscategory.RoomsCategory')),
            ],
            options={
                'db_table': 'cost_meal_category_plan',
            },
        ),
    ]
